"""Export marble templates in a form the browser can load.

    python tools/export_web_templates.py

Writes web/templates.js. The desktop template set stores nine jittered copies of
every source cell; the browser gets five (centre plus the four axis offsets),
which halves the download and the matching cost while keeping the tolerance to
a pixel or two of misalignment that the jitter exists for.
"""

import base64
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sigmar.vision import (  # noqa: E402
    HP_SIGMA,
    JITTER,
    QUANT,
    TEMPLATE_FILE,
    TILE,
    TILE_RADIUS,
)

# Centre, and one step along each axis: indices into JITTER.
KEEP = [4, 1, 7, 3, 5]
OUT = Path(__file__).resolve().parents[1] / "web" / "templates.js"


def main() -> int:
    raw = np.load(TEMPLATE_FILE)
    kinds, strokes, colours = raw["kinds"], raw["strokes"], raw["colours"]

    keep = np.array([i for i in range(len(kinds)) if i % len(JITTER) in KEEP])
    kinds, strokes, colours = kinds[keep], strokes[keep], colours[keep]

    # Colours are unit vectors, so a signed byte holds them to ~1%.
    quantised_colours = np.clip(np.round(colours.astype(np.float32) * 127), -127, 127).astype(np.int8)

    payload = {
        "tile": int(TILE),
        "sigma": float(HP_SIGMA),
        "radius": float(TILE_RADIUS),
        "quant": float(QUANT),
        "colourQuant": 127.0,
        "count": int(len(kinds)),
        "kinds": "".join(str(k) for k in kinds),
        "strokes": base64.b64encode(strokes.tobytes()).decode(),
        "colours": base64.b64encode(quantised_colours.tobytes()).decode(),
    }
    OUT.write_text(
        "/* Generated by tools/export_web_templates.py -- do not edit. */\n"
        "const TEMPLATE_DATA = " + json.dumps(payload) + ";\n",
        encoding="utf-8",
    )
    tally: dict[str, int] = {}
    for k in payload["kinds"]:
        tally[k] = tally.get(k, 0) + 1
    print(f"{payload['count']} templates -> {OUT.name}, {OUT.stat().st_size / 1024:.0f} KB")
    print("  " + "  ".join(f"{k}:{n}" for k, n in sorted(tally.items())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
